### ISSUE TITLE
Error message when loading Add-on in Blender 2.93

### ISSUE THREAD

**Issue by StephanSiemen** [blendernc/blendernc-zip-install#1]
When saving a zip file from their git repo and try to load master.zip, I get this error

<img width="1117" alt="Screenshot 2021-06-23 at 13 57 37" src="https://user-images.githubusercontent.com/11062969/123102760-4ae3ec00-d42d-11eb-9bfa-06472e876eec.png">

**Comment by josuemtzmo** [comment]
Can you print the list of files located in `/Users/stephan/Library/Aplication\ Support/Blender2.93/scripts/addons/`?

With the current information, I believe the issue is that there are two different versions of `blendernc` within that directory. You will be able to solve this issue by removing the older version of the add-on. 

Additionally, I found another issue, where the installed add-on will be titled `blendernc-zip-install`, which is really annoying as that is the name of the folder within the zip file. In order to solve this, there are two options:

- Decompress, rename the folder to `blendernc`, compress, and then install. 
- Decompress, rename the folder to `blendernc`, and move it into `/Users/stephan/Library/Aplication\ Support/Blender2.93/scripts/addons/`.

I'm working in a way to better solve this issue.

**Comment by StephanSiemen** [comment]
Thanks @josuemtzmo ,

content of my blendernc folder below. I have now deleted the folder, re-installed the add-on and **after** I renamed the folder to "blendernc" it works!

Stephan

[06:57:22] stephan@bitzer:git> lr /Users/stephan/Library/Application\ Support/Blender/2.93/scripts/addons/blendernc 
total 200
drwxr-xr-x   7 stephan  staff    224 23 Jun 14:41 core/
drwxr-xr-x  14 stephan  staff    448 23 Jun 14:41 nodes/
-rw-r--r--   1 stephan  staff  31359 23 Jun 14:41 python_functions.py
-rw-r--r--   1 stephan  staff   1188 23 Jun 14:41 msg_errors.py
-rw-r--r--   1 stephan  staff   2170 23 Jun 14:41 handlers.py
-rw-r--r--   1 stephan  staff     23 23 Jun 14:41 __init__.py
-rw-r--r--   1 stephan  staff   4171 23 Jun 14:41 UI_operators.py
-rw-r--r--   1 stephan  staff   4462 23 Jun 14:41 blendernc.py
-rw-r--r--   1 stephan  staff    360 23 Jun 14:41 get_utils.py
-rw-r--r--   1 stephan  staff   1749 23 Jun 14:41 sockets.py
-rw-r--r--   1 stephan  staff  11122 23 Jun 14:41 operators.py
-rw-r--r--   1 stephan  staff   3013 23 Jun 14:41 image.py
-rw-r--r--   1 stephan  staff   3869 23 Jun 14:41 panels.py
-rw-r--r--   1 stephan  staff   9064 23 Jun 14:41 decorators.py

**Comment by josuemtzmo** [comment]
I have changed the distribution process of BlenderNC. In order to avoid issues with GitHub renaming folders based on the repository name and branch, only a compressed zip is provided within this repository. 

<img width="701" alt="Screen Shot 2021-06-24 at 9 20 50 am" src="https://user-images.githubusercontent.com/9144063/123179894-a06fd580-d4cd-11eb-89e0-8ed9ca33ebb4.png">
